on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}
  # Run this workflow once per day, at 06:00 UTC (Paris +2 hours: 8am local)
  schedule: [{cron: "0 6 * * *"}]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to Observable Cloud
        # This parameter to `--message` will use the latest commit message
        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          # Authentication information. See below for how to set this up.
          OBSERVABLE_TOKEN: ${{secrets.OBSERVABLE_TOKEN }}
      - name: Dowload history
        uses: actions/download-artifact@v4
        with:
          name: history.json
          path: ./src/data/history.json
  history:
    name: Upload history
    needs: job_1
    runs_on: ubuntu-latest
    steps:
      - shell: bash
      - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: history
        path: ./src/data/history.json
        
      
  
